use std::process::ExitCode;

use clap::{Parser, Subcommand};
use ranma::{config, ipc, theme};

/// A tiling window manager for the terminal: i3's tree, Hyprland's dwindle, in a PTY.
#[derive(Parser)]
#[command(version = concat!(env!("CARGO_PKG_VERSION"), " (", env!("RANMA_GIT_SHA"), ")"))]
struct Cli {
    /// Print the built-in default init.lua and exit. It is also the reference for every option.
    #[arg(long, conflicts_with_all = ["check_config", "dump_theme"])]
    dump_config: bool,

    /// With --dump-config: comment out every line, for pasting into your own
    /// init.lua as a reference that changes nothing until you uncomment it.
    #[arg(long, requires = "dump_config")]
    commented: bool,

    /// Load the config and theme, report any error, and exit.
    #[arg(long, conflicts_with = "dump_theme")]
    check_config: bool,

    /// Print the built-in default theme and exit.
    #[arg(long)]
    dump_theme: bool,

    #[command(subcommand)]
    command: Option<Command>,
}

/// Commands for the ranma this shell runs in (found through RANMA_SOCKET).
#[derive(Subcommand)]
enum Command {
    /// Show a toast, e.g. `make && ranma notify "build done"`.
    Notify {
        /// Draw it in the urgent style.
        #[arg(long, short)]
        urgent: bool,
        /// Seconds before it goes (default 5).
        #[arg(long, short)]
        timeout: Option<f64>,
        /// The message.
        #[arg(required = true)]
        text: Vec<String>,
    },
    /// Pull ranma's source and install it; with --check, only say whether there
    /// is anything new.
    Update {
        #[arg(long)]
        check: bool,
    },
    /// Run an action, spelled as in a bind: `ranma action "workspace 3"`.
    Action {
        #[arg(required = true)]
        action: Vec<String>,
    },
    /// Open a pane somewhere, e.g. `ranma open --session ai --workspace empty
    /// --cwd ~/projects/x --name x -- 'ai; exec zsh'`. One argument after `--`
    /// is a command line for the shell; several are a command and its arguments.
    Open {
        /// Switch to this session, creating it if there is none.
        #[arg(long)]
        session: Option<String>,
        /// Then to this workspace: a number, next, prev or empty.
        #[arg(long)]
        workspace: Option<String>,
        /// Name the pane.
        #[arg(long)]
        name: Option<String>,
        /// Name the workspace it lands in.
        #[arg(long)]
        workspace_name: Option<String>,
        /// Start in this directory instead of the focused pane's.
        #[arg(long)]
        cwd: Option<std::path::PathBuf>,
        /// What to run; the shell when left out.
        #[arg(last = true)]
        command: Vec<String>,
    },
}

/// The default config with every line of code commented out. Comments stay as
/// they are, so the result reads like the original but does nothing.
fn commented(src: &str) -> String {
    let mut out = String::from(
        "-- Every option ranma has, at its default, commented out: uncomment a line\n\
         -- (or a whole block) to change it. Generated by `ranma --dump-config\n\
         -- --commented`; rerun it after upgrading to see options added since.\n\n",
    );
    for line in src.lines() {
        let t = line.trim_start();
        if t.is_empty() || t.starts_with("--") {
            out.push_str(line);
        } else {
            out.push_str("-- ");
            out.push_str(line);
        }
        out.push('\n');
    }
    out
}

/// `ranma update`: report how far behind the source is, and (without --check)
/// run the same pull-and-install the in-ranma update does.
fn update(check: bool) -> ExitCode {
    use ranma::update::{BUILD_SHA, SOURCE_DIR, behind, install_command};
    let dir = std::path::Path::new(SOURCE_DIR);
    match behind(dir, BUILD_SHA, true) {
        Ok(b) if b.commits() == 0 => {
            println!("ranma is up to date ({BUILD_SHA}, from {SOURCE_DIR})");
            if check {
                return ExitCode::SUCCESS;
            }
        }
        Ok(b) => {
            println!(
                "ranma is {} commit(s) behind its source: {} upstream, {} in the checkout ({SOURCE_DIR})",
                b.commits(),
                b.upstream,
                b.local
            );
            if check {
                return ExitCode::SUCCESS;
            }
        }
        Err(e) => {
            eprintln!("ranma: cannot check for updates: {e:#}");
            if check {
                return ExitCode::FAILURE;
            }
        }
    }
    match std::process::Command::new("sh")
        .arg("-c")
        .arg(install_command())
        .status()
    {
        Ok(s) if s.success() => ExitCode::SUCCESS,
        _ => ExitCode::FAILURE,
    }
}

/// One argument is a command line as written; several are quoted one by one,
/// the way ssh treats what follows the host.
fn command_line(args: &[String]) -> Option<String> {
    match args {
        [] => None,
        [one] => Some(one.clone()),
        many => Some(
            many.iter()
                .map(|a| format!("'{}'", a.replace('\'', "'\\''")))
                .collect::<Vec<_>>()
                .join(" "),
        ),
    }
}

fn main() -> ExitCode {
    let cli = Cli::parse();

    if let Some(Command::Update { check }) = cli.command {
        return update(check);
    }

    if let Some(cmd) = cli.command {
        let request = match cmd {
            Command::Notify {
                urgent,
                timeout,
                text,
            } => ipc::toast_request(&text.join(" "), urgent, timeout),
            Command::Update { .. } => unreachable!("handled above"),
            Command::Action { action } => format!("action\n{}", action.join(" ")),
            Command::Open {
                session,
                workspace,
                name,
                workspace_name,
                cwd,
                command,
            } => {
                let workspace = match workspace.map(|w| ranma::action::parse_workspace(&w)) {
                    None => None,
                    Some(Ok(w)) => Some(w),
                    Some(Err(e)) => {
                        eprintln!("ranma: --workspace: {e}");
                        return ExitCode::FAILURE;
                    }
                };
                // The pane runs this with the shell, relative paths from here.
                let cwd = cwd.map(|c| std::path::absolute(&c).unwrap_or(c));
                ipc::open_request(&ipc::OpenSpec {
                    session,
                    workspace,
                    name,
                    workspace_name,
                    cwd,
                    command: command_line(&command),
                })
            }
        };
        return match ipc::send(&request) {
            Ok(()) => ExitCode::SUCCESS,
            Err(e) => {
                eprintln!("ranma: {e:#}");
                ExitCode::FAILURE
            }
        };
    }

    if cli.dump_config {
        if cli.commented {
            print!("{}", commented(config::DEFAULT_INIT_LUA));
        } else {
            print!("{}", config::DEFAULT_INIT_LUA);
        }
        return ExitCode::SUCCESS;
    }
    if cli.dump_theme {
        print!("{}", theme::DEFAULT_THEME_SRC);
        return ExitCode::SUCCESS;
    }

    let dir = config::config_dir();
    let cfg = match config::load(dir.as_deref()) {
        Ok(cfg) => cfg,
        Err(e) => {
            eprintln!("ranma: config error: {e:#}");
            return ExitCode::FAILURE;
        }
    };

    if cli.check_config {
        match &cfg.source {
            Some(p) => println!("config: {}", p.display()),
            None => println!(
                "config: built-in defaults only (no init.lua in {})",
                dir.as_deref()
                    .map(|d| d.display().to_string())
                    .unwrap_or_else(|| "any config directory".into())
            ),
        }
        println!("leader: {}", cfg.settings.leader);
        println!("theme:  {}", cfg.theme.name);
        println!("binds:  {}", cfg.binds.len());
        println!(
            "hooks:  {}",
            cfg.hooks.values().map(Vec::len).sum::<usize>()
        );
        println!("ok");
        return ExitCode::SUCCESS;
    }

    match ranma::app::run(cfg) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("ranma: {e:#}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::command_line;

    #[test]
    fn commented_defaults_run_as_nothing() {
        let out = super::commented(ranma::config::DEFAULT_INIT_LUA);
        // Every line is a comment or blank: loading it changes nothing.
        assert!(
            out.lines()
                .all(|l| l.trim().is_empty() || l.trim_start().starts_with("--"))
        );
        let cfg = ranma::config::load_from(None, None, Some(&out)).unwrap();
        let defaults = ranma::config::load_from(None, None, None).unwrap();
        assert_eq!(cfg.settings, defaults.settings);
        assert_eq!(cfg.binds.len(), defaults.binds.len());
        // And every setting is in there to uncomment.
        for key in [
            "leader",
            "theme",
            "layout",
            "preserve_split",
            "shell",
            "scrollback_lines",
            "sticky",
            "mouse",
            "updates",
            "update_check_hours",
        ] {
            assert!(
                out.contains(&format!("--   {key} =")) || out.contains(&format!("--     {key} =")),
                "{key}"
            );
        }
    }

    #[test]
    fn one_argument_is_a_command_line_several_are_quoted() {
        let s = |v: &[&str]| v.iter().map(|x| x.to_string()).collect::<Vec<_>>();
        assert_eq!(command_line(&[]), None);
        assert_eq!(
            command_line(&s(&["ai; exec zsh"])).as_deref(),
            Some("ai; exec zsh")
        );
        assert_eq!(
            command_line(&s(&["echo", "it's", "a b"])).as_deref(),
            Some("'echo' 'it'\\''s' 'a b'")
        );
    }
}
