# Writes the which-key text fixtures src/whichkey.rs tests against, from wk.py
# (the handoff's port of the layout) and gen.py (the folders handoff's config).
# Run from this directory: python3 fixtures.py. Rerun when the default binds
# change, after updating the D_* rows in wk.py to what they now show.
from wk import layout, text, DEFAULTS, STRIP, F_PANE, F_LAYOUTS
from gen import TOP, GIT, BR, EMPTY_TOP, EMPTY

CR = ['ctrl+b']


def panels(spec):
    out = []
    for name, groups, sw, sh, keys, border in spec:
        p = layout(groups, sw, sh, CR + keys, back=bool(keys))
        out.append('## ' + name + '\n' + '\n'.join(text(p, border)) + '\n')
    return out


def write(path, header, spec, sep):
    with open(path, 'w') as f:
        f.write(header + sep + sep.join(panels(spec)))


write('../WHICH_KEY_MOCK.txt',
      "# The which-key hint's panels for the default binds, cell for cell.\n"
      "# Drawn first by the design handoff (Which-key hint grid alignment.zip);\n"
      "# redrawn 2026-10-09 by its own layout, WHICH_KEY_FOLDERS/wk.py, when the\n"
      "# defaults gained settings, the tmux extras and two folders.\n"
      "# Regenerate with WHICH_KEY_FOLDERS/fixtures.py; src/whichkey.rs tests these.\n",
      [('80x24 rounded', DEFAULTS, 80, 24, [], True),
       ('80x24 none', DEFAULTS, 80, 24, [], False),
       ('120x35 rounded', DEFAULTS, 120, 35, [], True),
       ('200x50 rounded', DEFAULTS, 200, 50, [], True),
       ('40x15 flowed', DEFAULTS, 40, 15, [], True),
       ('80x24 pane rounded', F_PANE, 80, 24, ['x'], True),
       ('80x24 layouts rounded', F_LAYOUTS, 80, 24, ['y'], True)],
      '')

write('../WHICH_KEY_FOLDERS_MOCK.txt',
      "# Which-key folders: the handoff's panels, cell for cell.\n"
      "# Generated by the handoff's own generator, WHICH_KEY_FOLDERS/gen.py and wk.py,\n"
      "# through fixtures.py; redrawn 2026-10-09 over the new default binds.\n"
      "# The configuration they draw is the c159 example in src/whichkey.rs tests.\n",
      [('80x24 top rounded', TOP, 80, 24, [], True),
       ('80x24 git rounded', GIT, 80, 24, ['g'], True),
       ('80x24 git branches rounded', BR, 80, 24, ['g', 'b'], True),
       ('80x24 git none', GIT, 80, 24, ['g'], False),
       ('120x35 top rounded', TOP, 120, 35, [], True),
       ('120x35 git rounded', GIT, 120, 35, ['g'], True),
       ('200x50 top rounded', TOP, 200, 50, [], True),
       ('40x15 git flowed', GIT, 40, 15, ['g'], True),
       ('40x15 top flowed', TOP, 40, 15, [], True),
       ('120x35 empty folder in top rounded', EMPTY_TOP, 120, 35, [], True),
       ('80x24 empty folder open rounded', EMPTY, 80, 24, ['z'], True)],
      '\n')

write('../SCROLLING_LAYOUT_MOCK.txt',
      "# The scrolling layout's handoff: the which-key hint in a strip (board 05),\n"
      "# cell for cell. The boards' panes hold real programs' output; the tests\n"
      "# check their structure (src/app/mod.rs, strip tests) rather than their text.\n"
      "# Redrawn 2026-10-09 over the new default binds by WHICH_KEY_FOLDERS/fixtures.py.\n",
      [('120x30 strip rounded', STRIP, 120, 30, [], True)],
      '\n')
