.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH RANMA-KILL 1 "" "ranma 0.1.0" "ranma manual"
.SH NAME
ranma\-kill \- Quit the server NAME and everything in it, without asking
.SH SYNOPSIS
\fBranma kill\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Quit the server NAME and everything in it, without asking
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
The server\*(Aqs name, as \fBranma ls\fR lists it
.SH "SEE ALSO"
\fBranma\fR(1)
