.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH RANMA-TMUX 1 "" "ranma 0.1.0" "ranma manual"
.SH NAME
ranma\-tmux \- The tmux shim asked for by name: \fBranma tmux list\-panes \-F \*(Aq#{pane_id}\*(Aq\fR
.SH SYNOPSIS
\fBranma tmux\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIARGS\fR] 
.SH DESCRIPTION
The tmux shim asked for by name: \fBranma tmux list\-panes \-F \*(Aq#{pane_id}\*(Aq\fR
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIARGS\fR]
What tmux would be given: a command and its flags
.SH "SEE ALSO"
\fBranma\fR(1)
