.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH RANMA-UPDATE 1 "" "ranma 0.1.0" "ranma manual"
.SH NAME
ranma\-update \- Pull ranma\*(Aqs source and install it; with \-\-check, only say whether there is anything new
.SH SYNOPSIS
\fBranma update\fR [\fB\-\-check\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Pull ranma\*(Aqs source and install it; with \-\-check, only say whether there is anything new
.SH OPTIONS
.TP
\fB\-\-check\fR
Only say whether the source has anything new; install nothing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH "SEE ALSO"
\fBranma\fR(1)
