.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH RANMA-ACTION 1 "" "ranma 0.1.0" "ranma manual"
.SH NAME
ranma\-action \- Run an action, spelled as in a bind: \fBranma action "workspace 3"\fR
.SH SYNOPSIS
\fBranma action\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIACTION\fR> 
.SH DESCRIPTION
Run an action, spelled as in a bind: \fBranma action "workspace 3"\fR
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIACTION\fR>
The action and its arguments (joined by spaces), as a bind spells it
.SH "SEE ALSO"
\fBranma\fR(1)
