.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH RANMA-LS 1 "" "ranma 0.1.0" "ranma manual"
.SH NAME
ranma\-ls \- List the ranma servers, and which ones a terminal is showing
.SH SYNOPSIS
\fBranma ls\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List the ranma servers, and which ones a terminal is showing
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH "SEE ALSO"
\fBranma\fR(1)
